version: '3.8'

services:
  database:
    container_name: db_testTDC
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
#      - POSTGRES_DB=testTDC_DB
#      - TZ=Europe/Moscow
    image: postgres:15.2-alpine
